version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
      - "50000:50000"
    networks:
      - jenkins
    hostname: dev.jenkins
    volumes:
      - "~/dev/docker/projects/common/volumes/jenkins:/var/jenkins_home"
    user: "${CURRENT_UID}:${CURRENT_GID}"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 10s
networks:
  jenkins:
    name: jenkins
